# Site settings
title: "Nanaimo Handyman Services"
description: "Professional roofing, gutters, fences, and interior repair services in Nanaimo, Parksville, and surrounding areas. Get your free estimate today!"
url: "https://yourusername.github.io" # Replace with your GitHub username
baseurl: "/handyman" # Replace with your repository name

# Author information
author:
  name: "Nanaimo Handyman Services"
  email: "info@handymanservices.com"
  phone: "(250) XXX-XXXX"

# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

# GitHub Pages specific settings
github: [metadata]
safe: true
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - README.md
  - DEVELOPMENT_PLAN.md

# Include in processing
include:
  - _pages

# Pagination (commented out until jekyll-paginate is added)
# paginate: 5
# paginate_path: "/blog/:num/"

# Social media
social:
  facebook: "https://facebook.com/handymanservices"
  instagram: "https://instagram.com/handymanservices"
  twitter: "https://twitter.com/handymanservices"

# Service areas
service_areas:
  - "Nanaimo"
  - "Parksville"
  - "Qualicum Beach"
  - "Lantzville"
  - "Nanoose Bay"
  - "Bowser"
  - "Deep Bay"
  - "Fanny Bay"

# Simple multilingual setup
langs:
  en: "English"
  fr: "Français"
  uk: "Українська"
  ru: "Русский"
